service: inspec-scan

provider:
  name: aws
  runtime: ruby2.5
  region: us-east-1
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
    - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'

functions:
  inspec_scan:
    handler: handler.inspec_scan
    layers:
      - {Ref: InspecLambdaLayer }

environment:
  HOME: /tmp

layers:
  inspec:
    path: layer
